targets = [ "//:gil" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
version = "branch=master"
